### ISSUE TITLE
Problem with word segmentation

### ISSUE THREAD

**Issue by Soul-Immortal** [WING-NUS/slsql#3]
Hi, I have a problem when I reproduce your program and I don't know how to solve it.
The problem is that the word segmentation tool will decompose A340-300 into 3 elements, making the `len(sample['lemma']) != len(sample['ant']).`
I don't know how to ignore the participle of -, how did you solve this problem？
Thank you!
![image](https://user-images.githubusercontent.com/91257452/187894446-d37f53ce-a885-496f-b80c-089bd062db90.png)

**Comment by Soul-Immortal** [comment]
The problem occurs when I do run **_sh preprocess.sh_**

**Comment by MottoX** [comment]
Hi, you can check the tool version again. If the issue still exists, you can simply try skipping this sample which shouldn't make a big difference.
